import { NavigationBar } from "@/components/navigationbar/navigationbar";
import { Button } from "@/components/ui/button";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import type { Metadata } from "next";
import { Aldrich } from "next/font/google";
import "./globals.css";

const aldrich = Aldrich({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-aldrich",
});

export const metadata: Metadata = {
  title: "anti-drugs-briefing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${aldrich.variable} antialiased bg-teal-950 pt-1 bg-landing bg-cover font-aldrich`}
        >
          <header className="flex justify-end">
            <SignedOut>
              <div className="pr-12 pt-8">
                <SignInButton>
                  <Button variant="default" size="lg">
                    Sign In
                  </Button>
                </SignInButton>
              </div>
            </SignedOut>
          </header>

          <SignedIn>
            <div className="flex justify-between pr-4">
              <NavigationBar />
              <UserButton />
            </div>
            {children}
          </SignedIn>

          <SignedOut>
            <div className="flex flex-col gap-2 justify-center items-center text-4xl h-[350px] text-center text-white">
              <p>Welcome Soldiers 🇸🇬 </p>
              <p>Please sign in to access the content.</p>
            </div>
          </SignedOut>
        </body>
      </html>
    </ClerkProvider>
  );
}
